name: Release

on:
  push:
    tags: [ 'v*' ]
    branches: [ '*' ]
  pull_request:
    branches: [ main ]
jobs:
  go-test:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set up linux dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc libgtk-3-dev libayatana-appindicator3-dev

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: go test ./...

  release-matrix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            goos: darwin
            goarch: amd64
            suffix: tar.gz
            snfm: snfm-*-macos-x64.zip
          #- os: macos-latest
          #  goos: darwin
          #  goarch: arm64
          - os: windows-latest
            goos: windows
            goarch: amd64
            exesuffix: .exe
            suffix: zip
            snfm: snfm-*-windows-x64.zip
          - os: windows-latest
            goos: windows
            goarch: "386"
            exesuffix: .exe
            suffix: zip
          - os: windows-latest
            goos: windows
            goarch: arm
            exesuffix: .exe
            suffix: zip
          - os: windows-latest
            goos: windows
            goarch: arm64
            exesuffix: .exe
            suffix: zip
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            suffix: tar.xz
            snfm: snfm-*-linux-x64.zip
          #- os: ubuntu-latest
          #  goos: linux
          #  goarch: "386"
          #- os: ubuntu-latest
          #  goos: linux
          #  goarch: arm64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set up linux dependencies
        if: ${{ matrix.goos == 'linux' }}
        run: sudo apt-get update && sudo apt-get install -y gcc libgtk-3-dev libayatana-appindicator3-dev

      # stupid cross-platform nonsense:
      - run: echo "basename=sni-${{env.GITHUB_REF_SLUG}}-${{matrix.goos}}-${{matrix.goarch}}" >> $GITHUB_ENV
        if: ${{ matrix.goos != 'windows' }}
      - run: echo "basename=sni-${{env.GITHUB_REF_SLUG}}-${{matrix.goos}}-${{matrix.goarch}}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        if: ${{ matrix.goos == 'windows' }}

      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0

      - name: Generate Windows resources
        if: ${{ matrix.goos == 'windows' }}
        run: |
          cd cmd/sni
          go install github.com/tc-hib/go-winres@latest
          go-winres simply --icon icon/sni.ico --product-version git-tag --file-version git-tag --file-description "SNI" --product-name "Super Nintendo Interface" --copyright "© jsd1982 2021" --original-filename "sni"

      - name: Package Lua Bridge for distribution
        run: |
          mkdir ${{env.basename}}
          mkdir ${{env.basename}}/lua
          mkdir ${{env.basename}}/lua/x64
          mkdir ${{env.basename}}/lua/x86
          cp README.md ${{env.basename}}
          cp LICENSE ${{env.basename}}
          cp protos/sni/sni.proto ${{env.basename}}
          cp cmd/sni/apps.yaml ${{env.basename}}
          cp lua/Connector.lua ${{env.basename}}/lua

      - name: Copy in lua socket.dll dependencies for Windows
        if: ${{ matrix.goos == 'windows' }}
        run: |
          rm ${{env.basename}}/lua/Connector.lua
          cp lua/Connector.lua ${{env.basename}}/lua/x64
          cp lua/Connector.lua ${{env.basename}}/lua/x86
          cp lua/x64/* ${{env.basename}}/lua/x64
          cp lua/x86/* ${{env.basename}}/lua/x86

      - if: ${{ matrix.goos == 'windows' }}
        name: Build SNI
        run: |
          Set-Item -Path Env:GOOS -Value "${{matrix.goos}}"
          Set-Item -Path Env:GOARCH -Value "${{matrix.goarch}}"
          go build -ldflags="-H=windowsgui -X 'main.version=${{env.GITHUB_REF_SLUG}}' -X 'main.commit=${{env.GITHUB_SHA_SHORT}}' -X 'main.date=$(date +'%Y-%m-%dT%H:%M:%S')' -X 'main.builtBy=$(go version | cut -f3 -d ' ')'" -o ./${{env.basename}}/sni${{matrix.exesuffix}} ./cmd/sni

      - if: ${{ matrix.goos != 'windows' }}
        name: Build SNI
        run: >
          GOOS=${{matrix.goos}} GOARCH=${{matrix.goarch}} go build
          -ldflags="-X 'main.version=${{env.GITHUB_REF_SLUG}}' -X 'main.commit=${{env.GITHUB_SHA_SHORT}}' -X 'main.date=$(date +'%Y-%m-%dT%H:%M:%S')'"
          -o ./${{env.basename}}/sni
          ./cmd/sni

      # cross-platform tar.gz creator:
      #- name: Create ${{env.basename}}.tar.gz
      #  run: >
      #    go run
      #    .github/scripts/tar.go
      #    -z
      #    -o ${{env.basename}}.tar.gz
      #    -strip ${{env.basename}}/
      #    ${{env.basename}}/

      - name: Download SNFM
        if: ${{ matrix.snfm }}
        run: gh release download --repo zig-for/snfm --pattern ${{ matrix.snfm }} --dir ${{ runner.temp }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Extract SNFM
        if: ${{ matrix.snfm }}
        run: 7z x -o"${{env.basename}}" "${{ runner.temp }}/${{ matrix.snfm }}" 

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.basename}}
          path: ${{env.basename}}/
          
      - name: Package ${{env.basename}}.${{matrix.suffix}} for MacOS
        if: ${{ matrix.os == 'macos-latest' && github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v') }}
        run: tar cJf ${{env.basename}}.${{matrix.suffix}} ${{env.basename}}/

      - name: Package ${{env.basename}}.${{matrix.suffix}} for Linux
        if: ${{ matrix.os == 'ubuntu-latest' && github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v') }}
        run: tar cJf ${{env.basename}}.${{matrix.suffix}} ${{env.basename}}/

      - name: Package ${{env.basename}}.${{matrix.suffix}} for Windows
        if: ${{ matrix.os == 'windows-latest' && github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v') }}
        run: Compress-Archive -DestinationPath ${{env.basename}}.${{matrix.suffix}} -Path ${{env.basename}}/*

      - name: Upload binaries to release
        if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.GITHUB_REF_SLUG }}
          overwrite: true
          asset_name: ${{env.basename}}.${{matrix.suffix}}
          file: ${{ github.workspace }}/${{env.basename}}.${{matrix.suffix}}


  manylinux2014:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set up linux dependencies
        run: |
          # manylinux2014 is based on centos 7, so we use yum
          yum -y install libappindicator libappindicator-devel libappindicator-gtk3 libappindicator-gtk3-devel gtk3-devel libdbusmenu-gtk3 libdbusmenu-gtk3-devel

      - run: echo "basename=sni-${{env.GITHUB_REF_SLUG}}-manylinux2014-amd64" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0

      - name: Collect files
        run: |
          mkdir ${{env.basename}}
          mkdir ${{env.basename}}/lua
          # mkdir ${{env.basename}}/lua/x64
          # mkdir ${{env.basename}}/lua/x86
          cp README.md ${{env.basename}}
          cp LICENSE ${{env.basename}}
          cp protos/sni/sni.proto ${{env.basename}}
          cp cmd/sni/apps.yaml ${{env.basename}}
          cp lua/Connector.lua ${{env.basename}}/lua
          # TODO: luasocket.so
          echo -e "\n--\nlibappindicator, libindicator and libdbusmenu are licensed under LGPL, see" >> ${{env.basename}}/LICENSE
          echo "https://launchpad.net/libappindicator/" >> ${{env.basename}}/LICENSE
          echo "https://launchpad.net/libindicator/" >> ${{env.basename}}/LICENSE
          echo "https://launchpad.net/libdbusmenu/" >> ${{env.basename}}/LICENSE
          cp -L /lib64/libappindicator3.so.1 ${{env.basename}}
          cp -L /lib64/libindicator3.so.7 ${{env.basename}}
          cp -L /lib64/libdbusmenu-glib.so.4 ${{env.basename}}
          cp -L /lib64/libdbusmenu-gtk3.so.4 ${{env.basename}}

      - name: Build SNI
        run: >
          CGO_LDFLAGS="$CGO_LDFLAGS -Wl,-rpath=. -Wl,--gc-sections"
          GOARCH=amd64 go build -tags=legacy_appindicator
          -ldflags="-X 'main.version=${{env.GITHUB_REF_SLUG}}' -X 'main.commit=${{env.GITHUB_SHA_SHORT}}' -X 'main.date=$(date +'%Y-%m-%dT%H:%M:%S')'"
          -o ./${{env.basename}}/sni
          ./cmd/sni

      - name: Package ${{env.basename}}.tar.xz for Linux
        run: |
          ldd ${{env.basename}}/sni
          tar cJf ${{env.basename}}.tar.xz ${{env.basename}}/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.basename}}.tar.xz
          path: ${{github.workspace}}/${{env.basename}}.tar.xz

      - name: Upload binaries to release
        if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.GITHUB_REF_SLUG }}
          overwrite: true
          asset_name: ${{env.basename}}.tar.xz
          file: ${{github.workspace}}/${{env.basename}}.tar.xz
